### ISSUE TITLE
Exception in Sketch 3.4.4

### ISSUE THREAD

**Issue by oblq** [abynim/Xport#2]
I've encountered an exception in Sketch 3.4.4:
Exception: TypeError: MSSliceMaker.sliceFromExportSize_layer_inRect_ is not a function. 

xPort send to xCode an empty imageSet and duplicate the layer inside the project.

Solved by renaming the function as follow:
 [MSSliceMaker sliceFromExportSize:exportSize layer:layer inRect:finalRect useIDForName:false];

Located in common.js at line 646

**Comment by abynim** [comment]
Thanks for reporting the issue, and for finding the solution. Just pushed a new version with this fix.

**Comment by oblq** [comment]
Invaluable plugin! 
Thanks to you
