### ISSUE TITLE
Impossible to drag n drop the Xcode project in the popup

### ISSUE THREAD

**Issue by sarahlafeuil-aufem** [abynim/Xport#7]
Hi
My previous version was Sketch 4.0 and it was working with the pluggin since a few days.... So I
've upgrade to Sketch 4.1 and the new version of Xport, but it doesn't work either.
I just can't drag and drop anything in the area.
No error or warning message. Nothing happened.

Thank you for your help !

**Comment by abynim** [comment]
@sarahlafeuil-aufem just pushed an update with a fix. Please download the plugin again and reinstall. Let me know if it works for you.
